title: Blog
description: Markdown posts published via mdpost
theme: minima
permalink: /:slug/

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
